backend:
  name: git-gateway
  branch: main

media_folder: "uploads"
public_folder: "/uploads"

collections:
  - name: "posts"
    label: "Публикации"
    folder: "posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    format: "json"
    fields:
      - { label: "Заголовок", name: "title", widget: "string" }
      - { label: "Дата публикации", name: "date", widget: "datetime", date_format: "DD.MM.YYYY", time_format: false }
      - { label: "Текст записи", name: "body", widget: "text" }
      - label: "Тип медиа"
        name: "media_type"
        widget: "select"
        options: ["none", "musescore", "youtube", "audio", "image"]
        default: "none"
      - { label: "Ссылка на медиа / Embed URL", name: "media_url", widget: "string", required: false }